name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  CLANG_VERSION: 21

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - name: Set up Clang ${{ env.CLANG_VERSION }}
        env:
          TEMP_DIR: ${{ runner.temp }}
        run: |
          clang_version=${{ env.CLANG_VERSION }}
          sudo apt-get update
          wget https://apt.llvm.org/llvm.sh -O "$TEMP_DIR/llvm_install.sh"
          chmod +x "$TEMP_DIR/llvm_install.sh"
          if sudo "$TEMP_DIR/llvm_install.sh" "$clang_version"; then
            sudo apt-get install -y clang-"$clang_version" \
                                    clang-format-"$clang_version" \
                                    clang-tidy-"$clang_version" \
                                    clang-tools-"$clang_version" \
            || exit 1
          else
            echo "Installation from script failed."
            exit 1
          fi
          echo "CC=clang-$clang_version" >> $GITHUB_ENV
          echo "CXX=clang++-$clang_version" >> $GITHUB_ENV
      - name: Set up MLIR
        uses: munich-quantum-software/setup-mlir@fc08baf0a172e98008e6528d465de3b5dd99bc68 # v1.4.1
        with:
          llvm-version: 22.1.8
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build
      - name: Run cpp-linter
        uses: cpp-linter/cpp-linter-action@8e85cd02c8c3fe3ae527c94b5683fe2366b144ed # v2.20.0
        id: linter
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          database: build
          files-changed-only: true
          ignore: "build|include"
          step-summary: true
          style: ""
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          tidy-checks: ""
          version: ${{ env.CLANG_VERSION }}
      - if: steps.linter.outputs.checks-failed > 0
        run: echo "Linter found errors" && exit 1
